/*
 * Coin Name Setting JS
 *
 */

const coinNameKR = {
    name: {
        BTC: '비트코인',
        ETH: '이더리움',
        ADA: '에이다',
        DOGE: '도지코인',
        XRP: '리플',
        DOT: '폴카닷',
        BCH: 'BT캐시',
        UNI: '유니스왑',
        LTC: '라이트코인',
        LINK: '체인링크',
        XLM: '스텔라루멘',
        ETC: '이더리움클래식',
        VET: '비체인',
        THETA: '쎄타코인',
        TRX: '트론',
        EOS: '이오스',
        AAVE: '에이브',
        MKR: '메이커',
        KLAY: '클레이튼',
        BSV: 'BT에스브이',
        XTZ: '테조스',
        ALGO: '알고랜드',
        CRO: '크립토닷컴체인',
        ATOM: '코스모스',
        LUNA: '루나',
        BTT: '비트토렌트',
        COMP: '컴파운드',
        WAVES: '웨이브',
        XEM: '넴',
        SNX: '신세틱스',
        YFI: '연파이낸스',
        CHZ: '칠리즈',
        TFUEL: '쎄타퓨엘',
        SUSHI: '스시스왑',
        ZIL: '질리카',
        MANA: '디스트럴랜드',
        BAT: '베이직어텐션토큰',
        GRT: '더그래프',
        BTG: 'BT골드',
        ENJ: '엔진코인',
        QTUM: '퀀텀',
        ONT: '온톨로지',
        OMG: '오미세고',
        UMA: '우마',
        ZRX: '제로엑스',
        ANKR: '앵커',
        ICX: '아이콘',
        BCD: 'BT다이아몬드',
        ORC: '오르빗체인',
        IOST: '이오스트',
        RLC: '아이젝',
        LRC: '루프링',
        ELF: '엘프',
        KNC: '카이버',
        GLM: '골렘',
        WAXP: '왁스',
        POWR: '파워렛저',
        STRAX: '스트라티스',
        REP: '어거',
        CTXC: '코르텍스',
        WTC: '월튼체인',
        LOOM: '룸네트워크',
        TRUE: '트루체인',
        RNT: '원트루넷',
        MTL: '메탈',
        TMTG: '더마이다스터치골드',
        STEEM: '스팀',
        PCM: '프레시움'

    },
};

export { coinNameKR };